# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: CodingDojo - DataScience
site_url: https://github.com/fralfaro/CodingDojo-DataScience
site_author: Francisco Alfaro
site_description: Curso Data Science 2022 - 2023

# Repository
repo_name: fralfaro/CodingDojo-DataScience
repo_url: https://github.com/fralfaro/CodingDojo-DataScience
edit_uri: ''



# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: images/logo_cd.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search


# TOC
nav:
    - Home: index.md
    - 1-PythonBasics/1-PythonBasics.ipynb
    - 1.5-numpy/1.5-numpy.ipynb
    - 2-Pandas/2-Pandas.ipynb
    - 3-Matplotlib/3-Matplotlib.ipynb
    - 4-StatisticalInference/4-StatisticalInference.ipynb
    - 5-IntroML/5-IntroML.ipynb
    - 6-RegressionModels/6-RegressionModels.ipynb
    - 7-ClassificationModels/7-ClassificationModels.ipynb
    - 8-Boosting/8-Boosting.ipynb
    - 9-UnsupervisedLearning/9-UnsupervisedLearning.ipynb
    - 10-DimensionalityReduction/10-DimensionalityReduction.ipynb
    - 11-NeuralNetworks/11-NeuralNetworks.ipynb
    - SQL:
        - 12-SQL/12-SQL-md.md
        - 12-SQL/12-SQL.ipynb



